### ISSUE TITLE
有一个问题

### ISSUE THREAD

**Issue by kuiniela** [lllyin/weread-dailyquestion-helper#3]
问题: 南宋著名的爱国
正确答案: 辛弃疾
概率: 范仲淹 :14.3%    辛弃疾 :85.7%    
依据: 国诗人南宋爱国诗词-文学词典-可可诗词网2019年5月14日此外,南宋爱国诗人还有辛弃疾(已于豪放词派介绍)、陈亮、刘辰翁、谢枋得、谢翱等,这里不再一一赘述。www.kekeshic
Traceback (most recent call last):
  File "D:/Program Files (x86)/weread-dailyquestion-helper-main/main.py", line 71, in <module>
    cc.run(appImg, answ, rightAnswer)
  File "D:\Program Files (x86)\weread-dailyquestion-helper-main\process\Click.py", line 36, in run
    locations = [v for v in locations]
  File "D:\Program Files (x86)\weread-dailyquestion-helper-main\process\Click.py", line 36, in <listcomp>
    locations = [v for v in locations]
  File "C:\ProgramData\Anaconda3\lib\site-packages\pyscreeze\__init__.py", line 257, in _locateAll_opencv
    raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max())
pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.628)

进程已结束，退出代码为 1
这啥意思呀@lllyin

**Comment by lllyin** [comment]
> 问题: 南宋著名的爱国 正确答案: 辛弃疾 概率: 范仲淹 :14.3% 辛弃疾 :85.7% 依据: 国诗人南宋爱国诗词-文学词典-可可诗词网2019年5月14日此外,南宋爱国诗人还有辛弃疾(已于豪放词派介绍)、陈亮、刘辰翁、谢枋得、谢翱等,这里不再一一赘述。www.kekeshic Traceback (most recent call last): File "D:/Program Files (x86)/weread-dailyquestion-helper-main/main.py", line 71, in cc.run(appImg, answ, rightAnswer) File "D:\Program Files (x86)\weread-dailyquestion-helper-main\process\Click.py", line 36, in run locations = [v for v in locations] File "D:\Program Files (x86)\weread-dailyquestion-helper-main\process\Click.py", line 36, in locations = [v for v in locations] File "C:\ProgramData\Anaconda3\lib\site-packages\pyscreeze__init__.py", line 257, in _locateAll_opencv raise ImageNotFoundException('Could not locate the image (highest confidence = %.3f)' % result.max()) pyscreeze.ImageNotFoundException: Could not locate the image (highest confidence = 0.628)
> 
> 进程已结束，退出代码为 1 这啥意思呀@lllyin

建议你用这个作者的哦，我这是适配macOS的，没在Windows用过
https://github.com/maotoumao/weread-dailyquestion-helper
